apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4411-go-helloworld-2:f3cbc55da11e379bbaec7f74cfc85e9cc5233984@sha256:f66019f465eb08ffedb1fc1e2da2f45f61a29a48cef22f175927bca3a7ef5ecby
        name: go-helloworld-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-helloworld-2
  type: NodePort
